# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler for Feedbackable contributions
on: 
  push: 
    branches:
      - "2021" ## TO BE UPDATED MANUALLY (GitHub workflows don't provide dynamic access to the name of the default branch :( )
  pull_request:
    branches:
      - "2021" ## SAME

jobs:
  label-feedback:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "2021"
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: '3.7.7'
    - name: install dependencies
      run: pip install PyGithub 
    - name: run python script 
      run: python .github/workflows/script_label.py ${{ secrets.GITHUB_TOKEN }}

    
